### ISSUE TITLE
No need to wait after Wire.requestFrom()

### ISSUE THREAD

**Issue by Koepel** [Lauszus/BalancingRobotFullSize#2]
In the file "I2C.cpp" there is a timeout with millis() and Wire.available() after the Wire.requestFrom(). That is not needed and can be removed.

When the Wire.requestFrom() returns, the I2C transaction has completely finished and the data is waiting in a buffer in the Wire library.

This is the shortest option:
```
  Wire.requestFrom(address, nbytes, (uint8_t)true); // Send a repeated start and then release the bus after reading
  Wire.readBytes( data, nbytes);
  return 0; // Success
```
This is with using the normal Wire.read() and with testing the number of received bytes:
```
  Wire.requestFrom(address, nbytes, (uint8_t)true); // Send a repeated start and then release the bus after reading
  if (Wire.available() != nbytes) {
    Serial.println(F("i2cRead bus error"));
    return 5; // This error value is not already taken by endTransmission
  }
  for (uint8_t i = 0; i < nbytes; i++) {
    data[i] = Wire.read();
  }
  return 0; // Success
```

**Comment by Lauszus** [comment]
@Koepel thanks. I have seen your other issues as well: https://github.com/TKJElectronics/Example-Sketch-for-IMU-including-Kalman-filter/issues/7 and https://github.com/TKJElectronics/KalmanFilter/issues/9, just been to busy to look into it.

Please submit a pull request to: https://github.com/TKJElectronics/KalmanFilter and I'll be happy to merge it.

**Comment by Lauszus** [comment]
Btw the reason I didn't use the "readBytes" function was because the code was written before the Wire library inherited the Stream class.

**Comment by Lauszus** [comment]
However it should probably return something like this instead:
```C++
return Wire.readBytes(data, nbytes) != nbytes;
```

**Comment by Koepel** [comment]
That is very short and with a test. Nice!

The Wire.readBytes() might not be compatible with every implementation of every Wire compatible library. Personally, I would like to promote the use of Wire.readBytes() if it didn't have consequences: https://github.com/arduino/Arduino/issues/6652

**Comment by Lauszus** [comment]
@Koepel can't you just set the timeout to 0 i.e:
```C++
Wire.setTimeout(0);
```
Of course there is going to be a little overhead, but I think we should use it anyway for simplicity.

**Comment by Koepel** [comment]
Yes, that would prevent a delay. But I don't know how compatible that is with other (more or less compatible) Wire libraries. It will be a temporary solution, I think it should be fixed in the Arduino library.

**Comment by Lauszus** [comment]
Since this does not have real benefits and the code in the library have been proven to work with multiple different kind of microcontrollers, then I see no real benefit by changing it. If you really want to change it, then you can submit a PR and do some testing.
